/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import lesson1.FirstLesson;
import lesson2.SecondLesson;


public class App {

    public static void main(String[] args) {

        System.out.println("Lesson 1 - \n");

        FirstLesson.main();

        System.out.println("\nLesson 2 - \n");

        SecondLesson.main();

    }
}
