/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    // Answer why there is "static" keyword in the method definition here?
    public static String getGreeting() {
        return "Hello world.";
    }

    // Answer why there is "static" keyword in the method definition here?
    public static int addTwoNumbers(int number1, int number2){
        return number1+number2;
    }

    public static void main(String[] args) {
        System.out.println(getGreeting());
        System.out.println(addTwoNumbers(10, 20));
    }
}
