/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAddTwoNumbers(){
        App classUnderTest = new App();
        int out = classUnderTest.addTwoNumbers(10, 20);
        assertEquals("10 + 20 must be 30", 30, out);
    }
}
